//#error Generation error: Message: Object reference not set to an instance of an object.

//AppDomain Information: 
//	Name: AppDomainForTestGeneration
//	ConfigFile: C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\plugincompability.config
//	BaseDirectory: C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools

//Loaded Assemblies:
//Fullname | Location | Codebase
//CommandLine, Version=2.2.1.0, Culture=neutral, PublicKeyToken=de6f01bd326f8c32 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\CommandLine.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/CommandLine.DLL
//CommandLine, Version=2.3.0.0, Culture=neutral, PublicKeyToken=de6f01bd326f8c32 | C:\Users\Sathya\AppData\Local\Microsoft\VisualStudio\15.0_7d97a550\Extensions\cckfdjnb.xm4\CommandLine.dll | file:///C:/Users/Sathya/AppData/Local/Microsoft/VisualStudio/15.0_7d97a550/Extensions/cckfdjnb.xm4/CommandLine.DLL
//Gherkin, Version=5.0.0.0, Culture=neutral, PublicKeyToken=86496cfa5b4a5851 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\Gherkin.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/Gherkin.DLL
//mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll | file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
//Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\Newtonsoft.Json.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/Newtonsoft.Json.DLL
//Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed | C:\Users\Sathya\AppData\Local\Microsoft\VisualStudio\15.0_7d97a550\Extensions\cckfdjnb.xm4\Newtonsoft.Json.dll | file:///C:/Users/Sathya/AppData/Local/Microsoft/VisualStudio/15.0_7d97a550/Extensions/cckfdjnb.xm4/Newtonsoft.Json.DLL
//System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
//System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
//System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
//System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
//System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
//System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
//System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
//System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
//System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 | C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll | file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
//TechTalk.SpecFlow, Version=2.4.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\TechTalk.SpecFlow.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/TechTalk.SpecFlow.DLL
//TechTalk.SpecFlow.Generator, Version=2.4.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\TechTalk.SpecFlow.Generator.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/TechTalk.SpecFlow.Generator.DLL
//TechTalk.SpecFlow.Parser, Version=2.4.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\TechTalk.SpecFlow.Parser.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/TechTalk.SpecFlow.Parser.DLL
//TechTalk.SpecFlow.Reporting, Version=2.4.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\TechTalk.SpecFlow.Reporting.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/TechTalk.SpecFlow.Reporting.DLL
//TechTalk.SpecFlow.Utils, Version=2.4.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | C:\Code\Career\Testing\CodeTest_SQS\SQS.TestSuite\packages\SpecFlow.2.4.0\tools\TechTalk.SpecFlow.Utils.dll | file:///C:/Code/Career/Testing/CodeTest_SQS/SQS.TestSuite/packages/SpecFlow.2.4.0/tools/TechTalk.SpecFlow.Utils.DLL
//TechTalk.SpecFlow.VisualStudio.CodeBehindGenerator, Version=2017.2.7.0, Culture=neutral, PublicKeyToken=0778194805d6db41 | C:\Users\Sathya\AppData\Local\Microsoft\VisualStudio\15.0_7d97a550\Extensions\cckfdjnb.xm4\TechTalk.SpecFlow.VisualStudio.CodeBehindGenerator.exe | file:///C:/Users/Sathya/AppData/Local/Microsoft/VisualStudio/15.0_7d97a550/Extensions/cckfdjnb.xm4/TechTalk.SpecFlow.VisualStudio.CodeBehindGenerator.exe

//System.NullReferenceException: Object reference not set to an instance of an object.
//   at TechTalk.SpecFlow.Generator.UnitTestFeatureGenerator.GenerateUnitTestFixture(SpecFlowDocument document, String testClassName, String targetNamespace)
//   at TechTalk.SpecFlow.Generator.TestGenerator.GenerateTestFileCode(FeatureFileInput featureFileInput)
//   at TechTalk.SpecFlow.Generator.TestGenerator.GetGeneratedTestCode(FeatureFileInput featureFileInput)
//   at TechTalk.SpecFlow.Generator.TestGenerator.GenerateTestFileWithExceptions(FeatureFileInput featureFileInput, GenerationSettings settings)
//   at TechTalk.SpecFlow.Generator.ErrorHandlingTestGenerator.GenerateTestFile(FeatureFileInput featureFileInput, GenerationSettings settings)